# Logistic Regression (Titanic_pydatatset)



https://pydataset.readthedocs.io/en/latest/index.html 


Dataset is for educational purposes, mainly. It tries to help those approaching Data Science in Python for the first time, who must deal with common (and time consuming) data preparation tasks.

In [1]:
!pip install pydataset

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002650B8550F0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pydataset/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002650B8553C0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pydataset/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002650B8555D0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pydataset/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002650B8556C0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pydataset/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002650B855840>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pydataset/
ERROR: Could not find a version that satisfies the requirement pydataset (from versions: none)
ERROR: No matching distribution found for pydataset

In [4]:
# Import Statements
#from pydataset import data
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [6]:
#Get the data
titanic = pd.read_csv('titanic.csv') #data('titanic')
titanic.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
649,650,1,3,"Stanley, Miss. Amy Zillah Elsie",female,23.0,0,0,CA. 2314,7.5500,NaN,S
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
547,548,1,2,"Padro y Manent, Mr. Julian",male,NaN,0,0,SC/PARIS 2146,13.8625,NaN,C
304,305,0,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S

In [7]:
#Feature Engineering (One hot encoding)
titanic = pd.get_dummies(titanic, drop_first=True) #there is no class one
titanic.sample(15)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)","Name_Abelson, Mr. Samuel",...,Cabin_F G63,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Embarked_Q,Embarked_S
3,4,1,1,35.0,1,0,53.1000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
306,307,1,1,NaN,0,0,110.8833,False,False,False,...,False,False,False,False,False,False,False,False,False,False
46,47,0,3,NaN,1,0,15.5000,False,False,False,...,False,False,False,False,False,False,False,False,True,False
104,105,0,3,37.0,2,0,7.9250,False,False,False,...,False,False,False,False,False,False,False,False,False,True
732,733,0,2,NaN,0,0,0.0000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
564,565,0,3,NaN,0,0,8.0500,False,False,False,...,False,False,False,False,False,False,False,False,False,True
749,750,0,3,31.0,0,0,7.7500,False,False,False,...,False,False,False,False,False,False,False,False,True,False
386,387,0,3,1.0,5,2,46.9000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
689,690,1,1,15.0,0,1,211.3375,False,False,False,...,False,False,False,False,False,False,False,False,False,True
484,485,1,1,25.0,1,0,91.0792,False,False,False,...,False,False,False,False,False,False,False,False,False,False
532,533,0,3,17.0,1,1,7.2292,False,False,False,...,False,False,False,False,False,False,False,False,False,False
509,510,1,3,26.0,0,0,56.4958,False,False,False,...,False,False,False,False,False,False,False,False,False,True
635,636,1,2,28.0,0,0,13.0000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
764,765,0,3,16.0,0,0,7.7750,False,False,False,...,False,False,False,False,False,False,False,False,False,True
577,578,1,1,39.0,1,0,55.9000,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [8]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(titanic.drop('survived_yes', axis=1), titanic['survived_yes'])

KeyError: "['survived_yes'] not found in axis"

In [8]:
#Train the model using the training data
solver='lbfgs'
LogReg = LogisticRegression(solver=solver)
LogReg.fit(X_train, y_train)

LogisticRegression()

In [9]:
#Predicting if a class-l child-age female survived
LogReg.predict(np.array([[0, 0, 1, 1]]))[0]

1

In [10]:
LogReg.score(X_test, y_test)

0.7629179331306991

In [11]:
#Understanfing the score
prediction = (LogReg.predict(X_test) > 0.5).astype(int)
np.sum(prediction == y_test) / len(y_test)

0.7629179331306991

In [ ]:
df_titan = pd.read_csv('titanic.csv', header=None)

In [ ]:
#Predicting if a class-l adult-age male survived
LogReg.predict(df_titan.values)

In [ ]:
#Scoring the model
LogReg.predict_proba(df_titan.values)

In [ ]:
accuracies = []
for max_iter in range(3, 10):
    LogReg = LogisticRegression(
        solver='newton-cg',
        max_iter=max_iter,
        random_state=42,
        tol=1e-100
    )
    
    LogReg.fit(X_train, y_train)
    accuracy = LogReg.score(X_test, y_test)
    accuracies.append(accuracy)

In [ ]:
plt.plot(accuracies)